receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
  metricstransform:
    transforms:
      - include: ^(.*)$$
        match_type: regexp
        action: update
        new_name: ${GITHUB_USER}.otel.$${1}
  filter:
    metrics:
      exclude:
        match_type: regexp
        metric_names:
          - .*\.jvm.*

exporters:
  debug:
    verbosity: normal
  otlphttp:
    endpoint: https://${DT_ENVIRONMENT_HOST}/api/v2/otlp
    headers:
      Authorization: "Api-Token ${DT_API_TOKEN}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp]
  #telemetry:
  #  logs:
  #    level: debug
